### ISSUE TITLE
Add Remember Me Box and Cookies

### ISSUE THREAD

**Issue by jaisal1024** [danielwatson6/swe-project#2]
> You commented in ./src/server/routes/login.py line 19 that we need to implement a remember me function. But then you added the login cookies, so isn't that done?

The cookies are deleted when the browser is closed. A "remember me" box can be used to make the cookies persist, but this is a tradeoff between UX and security

_Originally posted by @danielwatson6 in https://github.com/danielwatson6/swe-project/pull/1#issuecomment-559003180_

**Comment by jaisal1024** [comment]
I think security wise, its not an issue since our users will be using it on their password protected personal computers. I say we implement it for ease of use.

**Comment by danielwatson6** [comment]
@jaisal1024 reviewed, you can make the changes and merge
